services:
  nvim:
    command: "/bin/zsh"
    environment:
      XDG_CONFIG_HOME: "/workspace/.config/"
      TERM: "xterm-256color"
      # ZDOTDIR: "/workspace"
      HOME: "/workspace"
    extends:
      file: ../pytorch_cuda_opencv_ffcv_docker/compose.yaml
      service: ffcv
    build:
      context: .
      additional_contexts:
        pytorch: ../pytorch_cuda_opencv_ffcv_docker


  
